---
title: "compare_forest_loss_durations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(raster)
library(Matrix)
library(sparseMatrixStats)
library(Hmisc)

library(ggplot2)
library(cowplot)
```



```{r warning=FALSE}
pred_loss_1 <- readRDS(file = paste0("output/update/", "fd_1", "_pred_matrix.Rds"))
pred_loss_3 <- readRDS(file = paste0("output/update/", "fd_3", "_pred_matrix.Rds"))
pred_loss_5 <- readRDS(file = paste0("output/update/", "fd_5", "_pred_matrix.Rds"))

blank_seasia <- raster('data/clean/raster/SEAsia_extent.grd')

cols <- colorRampPalette(c("#55843b","#ffffbf", "#6c0043"))(100)
```


```{r fig.width=5, fig.height=10, dpi=400}
names(blank_seasia) <- "mean"

mean_comp <- c("1","3","5")

means <- list(colMeans2(pred_loss_1),
              colMeans2(pred_loss_3),
              colMeans2(pred_loss_5))




# Reduce 0s to NA (due to sparse matrix usage)
means <- lapply(means, function(m) {
  m[m==0] <- NA
  m
})

mean_df <- lapply(1:length(mean_comp), function(m_i) {
  as.data.frame(setValues(blank_seasia, means[[m_i]]),
                         xy=T) %>%
    mutate(group = mean_comp[m_i])
  }) %>% bind_rows()

diff_df <- mean_df %>%
  left_join(x = .,
            y = .,
            by = c("x","y"),
            suffix = c("_1","_2")) %>%
  mutate(mean_diff = mean_1 - mean_2) %>%
  filter(as.numeric(group_2) > as.numeric(group_1))


ggplot(diff_df, aes(x = x,y = y,fill = mean_diff)) +
  geom_raster() +
  scale_fill_gradientn(colors = cols, na.value='transparent',
                       limits = c(-0.3, 0.3)) +
  coord_fixed(expand = F) +
  theme(panel.grid = element_blank(),
        panel.background = element_rect('white'),
        legend.position = 'bottom',
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank()) +
  facet_grid(rows = vars(group_1, group_2),
             labeller = label_both) +
  ggtitle("group_1 mean - group_2 mean","Differing forest loss capture periods")

```