---
title: "model_interpretation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/data/gpfs/projects/punim1449/knowlesi_ruarai")
```




```{r}

library(iml)
library(dplyr)
library(seegSDM)
library(gbm)




m_list <- readRDS(paste0("output/update/bootstrap_outputs/",run_unique_name,"/1_brt_model_list.Rds"))

m_input_data <- readRDS(paste0("output/update/bootstrap_inputs/", run_unique_name, "/1_brt_data_list.Rds"))
m_input_data <- m_input_data[[1]]

bs_fun <- function(model_list, newdata){
  rowMeans(do.call(cbind,lapply(m_list, function(gbm_i) predict.gbm(gbm_i$model, newdata))))
}

y <- m_input_data$PA

host_index <- match("Host_species", names(m_input_data))

X <- m_input_data[,host_index:ncol(m_input_data)]



model = Predictor$new(m_list, predict.fun = bs_fun, data = X, y = y)
```


```{r message=FALSE, warning=FALSE}

auc_error = function(actual, predicted) 1 - Metrics::auc(actual, predicted)

imp = FeatureImp$new(model, loss = auc_error)
plot(imp)

```


## ALE / Conditional effect

```{r fig.width=12, fig.height=8, message=FALSE, warning=FALSE}
effect = FeatureEffects$new(model, method = "ale")

effect$plot()
```



## Shapley Values

```{r}

pred_raster <- brick("data/clean/raster_updated/prediction_SEA")
pred_df <- as.data.frame(pred_raster, xy=T)
pred_df$Host_species <- 3

non_na_rows <- which(!is.na(pred_df$SRTM_elevation))

sample_rows <- sample(non_na_rows, 2000)


plot(pred_raster[['SRTM_elevation']])
points(pred_df[sample_rows,c("x","y")], pch='.', col='blue')

```

```{r}
shap <- Shapley$new(model, sample.size=100)

```


```{r, message=FALSE, warning=FALSE}

library(doMC)

sample_row_data <- pred_df[sample_rows,] %>%
  dplyr::select(-c(x,y)) %>%
  dplyr::select(names(X))

registerDoMC(cores = 8)

shap_explains <- foreach(i=1:nrow(sample_row_data), 
                         .packages = c('iml'),
                         .inorder = F) %dopar% {
  shap$explain(sample_row_data[i,])
  
  shap$results
}


shap_all <- bind_rows(shap_explains)

shap_all <- shap_all  %>%
  mutate(feature_val = str_extract(feature.value, "(?<==).+$") %>%
           as.numeric())


shap_all$feature <- factor(shap_all$feature,levels = imp$results$feature)
```


```{r fig.width=12, fig.height=8, message=FALSE, warning=FALSE}

ggplot(shap_all) +
  geom_hline(yintercept=0, size=0.1, color='blue') +
  geom_point(aes(x = feature_val,
                 y = phi),
             size = 0.5, stroke = 0) +
  facet_wrap(~feature, scales="free_x") +
  theme_bw() 


```






