---
title: "model_run_summary"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(raster)
library(Matrix)
library(sparseMatrixStats)
library(Hmisc)
library(seegSDM)

library(ggplot2)
```



```{r warning=FALSE}
full_pred_matrix <- readRDS(file = paste0("output/update/", run_unique_name, "_pred_matrix.Rds"))
blank_seasia <- raster('data/clean/raster/SEAsia_extent.grd')

cols <- colorRampPalette(c("#55843b","#ffffbf", "#6c0043"))(100)
```


```{r fig.width=10, fig.height=8, dpi=400}
pred_means <- colMeans2(full_pred_matrix)
pred_sd <- colSds(full_pred_matrix)

pred_means[pred_means == 0] <- NA
pred_sd[pred_sd == 0] <- NA

plot(setValues(blank_seasia, pred_means), col = cols, zlim=c(0,1))
title("Predicted risk means", run_unique_name)

writeRaster(setValues(blank_seasia, pred_means),
            paste0("output/update/rasters/", run_unique_name, "_risk_mean.tif"),
            overwrite = TRUE,
            format = "GTiff")


plot(setValues(blank_seasia, pred_sd))
title("Predicted risk standard deviation", run_unique_name)


writeRaster(setValues(blank_seasia, pred_sd),
            paste0("output/update/rasters/", run_unique_name, "_risk_sd.tif"),
            overwrite = TRUE,
            format = "GTiff")
```

```{r}
hist(pred_means, xlab='Risk mean', main='', breaks=100)
title(run_unique_name)

hist(pred_sd, xlab='Risk SD', main='', xlim=c(0,0.3), breaks = 100)
title(run_unique_name)


```

```{r}
risk_freya <- raster('data/clean/raster/SEAsia.tif')
diff_means <- pred_means - risk_freya

plot(diff_means, col=cols, zlim=c(-0.5,0.5))
title("Change in risk (vs FS)", paste0(run_unique_name, " - FS Risk"))

hist(diff_means, xlab='Change in risk from original FS risk map', main='')
title(paste0(run_unique_name, " - FS Risk"), run_unique_name)
```

```{r}
# Change from arbitrary other dataset
comp_run <- "fd_1"

full_pred_matrix_comp <- readRDS(file = paste0("output/update/", comp_run, "_pred_matrix.Rds"))

comp_means <- colMeans2(full_pred_matrix_comp)

comp_diff_means <- pred_means - comp_means

plot(setValues(blank_seasia, comp_diff_means), col=cols, zlim=c(-0.5,0.5))
title(paste0("Change in risk (vs ", comp_run, ")"), paste0(run_unique_name, " - ", comp_run))

hist(comp_diff_means, xlab=paste0('Change in risk from ', run_unique_name), main='')
title(paste0(run_unique_name, " - ", comp_run), run_unique_name)


```


```{r}
model_stats <- do.call(rbind, 
                       lapply(list.files(paste0("output/update/model_stats/", run_unique_name)
                                         , full.names = TRUE),
                              read.csv))
model_stats <- model_stats[,-1]


print(paste0("CV AUC mean: ", round(mean(model_stats$auc),2)))

print(paste0("CV RMSE mean: ", round(mean(model_stats$rmse),2)))
```

```{r}
model_rel_inf <- do.call(rbind, 
                       lapply(list.files(paste0("output/update/model_rel_inf/", run_unique_name)
                                         , full.names = TRUE),
                              read.csv))
model_rel_inf <- model_rel_inf[,-1]
```


```{r}
model_rl_long <- model_rel_inf %>% pivot_longer(cols = everything())

means <- model_rl_long %>%
  group_by(name) %>%
  summarise(mean_rl = mean(value)) %>%
  arrange(desc(mean_rl))

model_rl_long$name <- factor(model_rl_long$name, levels = means$name)

ggplot(model_rl_long) +
  geom_jitter(aes(x = name, y = value), size=0.2, width=0.2, alpha=0.5) +
  theme(axis.text.x = element_text(angle = -45,hjust=0)) +
  xlab("Covariate") + ylab("Relative Influence")
```


```{r fig.width=10, fig.height=4, dpi=400}
covar_interest <- head(means$name, 5)

pred_raster <- brick("data/clean/raster_updated/prediction_SEA")

par(mfrow=c(1,2))
for(i_covar in covar_interest) {
  plot(setValues(blank_seasia, pred_means), col = cols, zlim=c(0,1))
  title("Predicted risk means", run_unique_name)
  
  
  plot(pred_raster[[i_covar]], col = viridisLite::viridis(10))
  title(i_covar, "covariate raster")
}

par(mfrow=c(1,2))
for(i_covar in covar_interest) {
  plot(setValues(blank_seasia, pred_means), col = cols, zlim=c(0,1))
  title("Predicted risk means", run_unique_name)
  
  
  plot(log(pred_raster[[i_covar]]+1,10), col = viridisLite::viridis(10))
  title(paste0(i_covar, " (log)"), "covariate raster")
}
```







